# Generated by Django 4.2.16 on 2026-07-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('DOCUMENT', 'Medical Document'), ('APPOINTMENT', 'Appointment'), ('AI_SUMMARY', 'AI Insight'), ('METRIC', 'Health Metric'), ('VACCINATION', 'Vaccination'), ('NOTE', 'Personal Note')], max_length=20)),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('source_app', models.CharField(blank=True, max_length=50)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'db_table': 'timeline_events',
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', '-event_date'], name='idx_timeline_patient_date'), models.Index(fields=['event_type'], name='idx_timeline_type')],
            },
        ),
    ]
