# Generated by Django 4.2.16 on 2026-07-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_ids', models.JSONField(blank=True, default=list)),
                ('category_filter', models.JSONField(blank=True, default=list)),
                ('scope', models.CharField(choices=[('SINGLE_DOC', 'Single Document'), ('CATEGORY', 'Category'), ('FULL_PROFILE', 'Full Profile')], default='FULL_PROFILE', max_length=20)),
                ('expiry_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('max_access_count', models.IntegerField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share Token',
                'verbose_name_plural': 'Share Tokens',
                'db_table': 'share_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accessor_ua', models.TextField(blank=True)),
                ('documents_viewed', models.JSONField(default=list)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='medical_records.sharetoken')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'db_table': 'access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('RADIOLOGY', 'Radiology / Imaging'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('VACCINATION', 'Vaccination'), ('DENTAL', 'Dental'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('CARDIOLOGY', 'Cardiology'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=300)),
                ('provider_type', models.CharField(blank=True, choices=[('HOSPITAL', 'Hospital'), ('LAB', 'Laboratory'), ('CLINIC', 'Clinic'), ('PHARMACY', 'Pharmacy'), ('OTHER', 'Other')], max_length=20)),
                ('file_s3_key', models.CharField(max_length=1000)),
                ('file_original_name', models.CharField(blank=True, max_length=500)),
                ('file_type', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('JPG', 'JPG'), ('PNG', 'PNG'), ('HEIC', 'HEIC')], max_length=10)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('upload_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Document',
                'verbose_name_plural': 'Medical Documents',
                'db_table': 'medical_documents',
                'ordering': ['-document_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'deleted_at'], name='idx_docs_patient'), models.Index(fields=['category'], name='idx_docs_category'), models.Index(fields=['-document_date'], name='idx_docs_date'), models.Index(fields=['upload_status'], name='idx_docs_status')],
            },
        ),
    ]
