# Generated by Django 4.2.16 on 2026-07-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldocument',
            name='file_s3_key',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_documents/'),
        ),
    ]
