# Generated by Django 4.2.16 on 2026-07-17 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True)),
                ('key_findings', models.JSONField(blank=True, default=list)),
                ('abnormal_flags', models.JSONField(blank=True, default=list)),
                ('extracted_values', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('llm_prompt_tokens', models.IntegerField(default=0)),
                ('llm_completion_tokens', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='medical_records.medicaldocument')),
            ],
            options={
                'verbose_name': 'AI Summary',
                'verbose_name_plural': 'AI Summaries',
                'db_table': 'ai_summaries',
            },
        ),
    ]
