# Generated by Django 4.2.16 on 2026-07-19 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('national_health_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=200)),
                ('insurance_policy_no', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('data_sharing_consent', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
                'db_table': 'patient_profiles',
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('metric_unit', models.CharField(blank=True, max_length=50)),
                ('normal_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('normal_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('recorded_at', models.DateField()),
                ('source', models.CharField(choices=[('DOCUMENT', 'Document'), ('MANUAL', 'Manual Entry'), ('DEVICE', 'Wearable Device')], default='DOCUMENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Metric',
                'verbose_name_plural': 'Health Metrics',
                'db_table': 'health_metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'metric_name'], name='idx_metrics_patient_metric'), models.Index(fields=['-recorded_at'], name='idx_metrics_recorded_at')],
            },
        ),
    ]
