# Generated by Django 4.2.16

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # ─── User Table ──────────────────────────────────────────────────────
        migrations.CreateModel(
            name='User',
            fields=[
                ('password',     models.CharField(max_length=128, verbose_name='password')),
                ('last_login',   models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(
                    default=False,
                    help_text='Designates that this user has all permissions without explicitly assigning them.',
                    verbose_name='superuser status',
                )),
                ('id',           models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email',        models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('phone',        models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='phone number')),
                ('role',         models.CharField(
                    choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin')],
                    default='PATIENT',
                    max_length=20,
                    verbose_name='role',
                )),
                ('is_active',    models.BooleanField(default=True, verbose_name='active')),
                ('is_staff',     models.BooleanField(default=False, verbose_name='staff status')),
                ('is_verified',  models.BooleanField(default=False, verbose_name='email verified')),
                ('mfa_enabled',  models.BooleanField(default=False, verbose_name='MFA enabled')),
                ('mfa_secret',   models.CharField(blank=True, max_length=64, null=True, verbose_name='MFA secret')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at',   models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at',   models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at',   models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('groups',       models.ManyToManyField(
                    blank=True,
                    help_text='The groups this user belongs to.',
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.group',
                    verbose_name='groups',
                )),
                ('user_permissions', models.ManyToManyField(
                    blank=True,
                    help_text='Specific permissions for this user.',
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.permission',
                    verbose_name='user permissions',
                )),
            ],
            options={
                'verbose_name':        'user',
                'verbose_name_plural': 'users',
                'db_table':            'users',
                'ordering':            ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.BaseUserManager()),
            ],
        ),

        # ─── UserProfile Table ───────────────────────────────────────────────
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user',               models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    related_name='profile',
                    serialize=False,
                    to=settings.AUTH_USER_MODEL,
                )),
                ('first_name',         models.CharField(max_length=100, verbose_name='first name')),
                ('last_name',          models.CharField(max_length=100, verbose_name='last name')),
                ('date_of_birth',      models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender',             models.CharField(
                    blank=True,
                    choices=[
                        ('MALE', 'Male'), ('FEMALE', 'Female'),
                        ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say'),
                    ],
                    max_length=25,
                    verbose_name='gender',
                )),
                ('blood_type',         models.CharField(
                    blank=True,
                    choices=[
                        ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'),
                        ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'),
                    ],
                    max_length=5,
                    verbose_name='blood type',
                )),
                ('allergies',          models.JSONField(blank=True, default=list, verbose_name='allergies')),
                ('chronic_conditions', models.JSONField(blank=True, default=list, verbose_name='chronic conditions')),
                ('current_medications', models.JSONField(blank=True, default=list, verbose_name='current medications')),
                ('emergency_name',     models.CharField(blank=True, max_length=200, verbose_name='emergency contact name')),
                ('emergency_phone',    models.CharField(blank=True, max_length=20, verbose_name='emergency contact phone')),
                ('emergency_relation', models.CharField(blank=True, max_length=50, verbose_name='emergency contact relation')),
                ('profile_photo_url',  models.URLField(blank=True, verbose_name='profile photo URL')),
                ('created_at',         models.DateTimeField(auto_now_add=True)),
                ('updated_at',         models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name':        'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table':            'user_profiles',
            },
        ),

        # ─── Indexes ─────────────────────────────────────────────────────────
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_users_role'),
        ),
    ]
