# Generated by Django 4.2.16 on 2026-07-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mfa_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mfa_secret',
        ),
    ]
