# Generated by Django 4.2.16 on 2026-07-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_last_login_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_alt_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='emergency alternate phone'),
        ),
    ]
