# Generated by Django 4.2.16 on 2026-07-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_emergency_alt_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='profile photo'),
        ),
    ]
