# Generated by Django 4.2.16 on 2026-07-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(choices=[('TREND_FORECAST', 'Metric Trend Forecast'), ('ANOMALY', 'Anomaly Detection'), ('DISEASE_RISK', 'Disease Risk Prediction'), ('DRUG_INTERACTION', 'Drug Interaction Warning')], max_length=30)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('is_flagged', models.BooleanField(default=False)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ML Prediction',
                'verbose_name_plural': 'ML Predictions',
                'db_table': 'ml_predictions',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('contributing_factors', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Score',
                'verbose_name_plural': 'Health Scores',
                'db_table': 'health_scores',
                'ordering': ['-computed_at'],
                'get_latest_by': 'computed_at',
            },
        ),
    ]
